FROM odoopbx/pbx:latest
ARG ODOO_VERSION=15.0
ARG ODOO_DB=odoopbx_15
ENV ODOO_VERSION=$ODOO_VERSION ODOO_DB=$ODOO_DB
ENV POSTGRES_AUTOSTART=true ODOO_AUTOSTART=true NGINX_AUTOSTART=true

RUN odoopbx install postgres \
    && odoopbx install odoo \
    && salt-call --local grains.set odoo:addons_init val=asterisk_plus_crm \
    && odoopbx install odoo.config \
    && odoopbx install nginx

COPY ./supervisor.conf /etc/supervisor/conf.d/odoo.conf
