name: DEMO
on:
  push:
    branches:
      - 12.0
      - 13.0
      - 14.0
      - 15.0

jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
      - name: Docker hub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN}}
      - if: github.ref_name == 15.0
        name: Build and push ${{ github.repository_owner }}/demo:${{ github.ref_name }}
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.demo
          push: true
          tags: |
            ${{ github.repository_owner }}/demo:latest
            ${{ github.repository_owner }}/demo:${{ github.ref_name }}
          build-args: |
            ODOO_VERSION=${{ github.ref_name }}
            ODOO_DB=demo_${{ github.ref_name }}
      - if: github.ref_name == 14.0 || github.ref_name == 13.0 || github.ref_name == 12.0
        name: Build and push ${{ github.repository_owner }}/demo:${{ github.ref_name }}
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.demo
          push: true
          tags: |
            ${{ github.repository_owner }}/demo:${{ github.ref_name }}
            ${{ github.repository_owner }}/demo:latest
          build-args: |
            ODOO_VERSION=${{ github.ref_name }}
            ODOO_DB=demo_${{ github.ref_name }}
